### ISSUE TITLE
🤔 Allow passing parameters to `fn()`

### ISSUE THREAD

**Issue by richardhj** [m-vo/contao-twig#8]
The `fe_page` template has a `FrontendTemplate#sections($key)` method to render a custom layout section.

Can you call this method inside a `fe_page.html.twig` template?

https://github.com/m-vo/contao-twig/blob/a82bc2e6d4143bf296f4a568efcaa3d4f2f82835/src/Twig/ContaoTemplateExtension.php#L21

**Comment by m-vo** [comment]
We should probably make these (2-3?) specific Contao template functions available as Twig functions (`contao_*`). 

I did something similar in https://github.com/contao/contao/pull/2612.
